import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function assertAccessible(page,label){const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();expect(results.violations,`${label}: ${results.violations.map(v=>`${v.id}(${v.nodes.length})`).join(', ')}`).toEqual([])}
async function start(page,name='سامر'){await page.goto('/');await page.getByRole('button',{name:/ابدأ المحاكاة|بدء جولة جديدة/}).click();await page.locator('article.scenario').filter({hasText:name}).getByRole('button',{name:'اختيار هذه الحالة'}).click()}
async function enterWork(page,name='سامر'){await start(page,name);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click()}
async function firstChoices(page){const samples=page.locator('.sample');for(let i=0;i<await samples.count();i++)await samples.nth(i).locator('button.choice').first().click()}
async function classify(page){const docs=page.locator('.doc').filter({has:page.locator('.sort')});for(let i=0;i<await docs.count();i++)await docs.nth(i).locator('.sort').first().click()}
async function answerQuestions(page){const count=await page.locator('select[data-q]').count();for(let i=0;i<count;i++)await page.locator('select[data-q]').nth(i).selectOption({index:1})}
async function rankPower(page){for(;;){const card=page.locator('fieldset.power-card');const axis=await card.locator('select[data-axis]').first().getAttribute('data-axis');const primary=axis==='risk'?'worker':axis==='quality'?'client':'platform';await card.locator(`select[data-party="${primary}"]`).selectOption('2');await page.getByRole('button',{name:/اعتماد هذا الترتيب|تحديث اعتماد هذا الترتيب/}).click();const next=page.getByRole('button',{name:'المحور التالي'});if(await next.count())await next.click();else break}}
test('landing, scenario, onboarding and work are accessible',async({page})=>{await page.goto('/');await assertAccessible(page,'home');await page.getByRole('button',{name:/ابدأ المحاكاة|بدء جولة جديدة/}).click();await assertAccessible(page,'scenario');await page.locator('article.scenario').filter({hasText:'سامر'}).getByRole('button',{name:'اختيار هذه الحالة'}).click();await assertAccessible(page,'onboarding');await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await assertAccessible(page,'work')});
test('no-work researcher evidence is accessible',async({page})=>{await enterWork(page,'سامر');await page.getByRole('button',{name:'إنهاء الوردية دون قبول عمل'}).click();await assertAccessible(page,'access no-work');await page.getByRole('button',{name:'ابدأ تحليل الوردية'}).click();await assertAccessible(page,'investigation case');await page.getByRole('button',{name:'ابدأ تصنيف الأدلة'}).click();await assertAccessible(page,'investigation evidence')});
test('ordinal power map and conclusion stay accessible',async({page},testInfo)=>{test.skip(testInfo.project.name.startsWith('mobile-'),'full Axe journey covered on desktop engines');await enterWork(page,'ليان');await page.getByRole('button',{name:'قبول',exact:true}).first().click();await firstChoices(page);await page.getByRole('button',{name:'إرسال العمل للمراجعة'}).click();await page.getByRole('button',{name:'رؤية أثر الأداء على فرص العمل'}).click();await page.getByRole('button',{name:'رؤية العرض الناتج عن هذا التحديث'}).click();await page.getByRole('button',{name:'أنهي الوردية الآن'}).click();await page.getByRole('button',{name:'الانتقال إلى المراجعة دون استراحة'}).click();await assertAccessible(page,'risk');await page.getByRole('button',{name:'متابعة إلى مراجعة جودة العمل'}).click();const skip=page.getByRole('button',{name:/متابعة إلى التسوية|المتابعة دون اعتراض/});await skip.first().click();await page.getByRole('button',{name:'إنهاء التسوية ومراجعة الوصول'}).click();await page.getByRole('button',{name:'ابدأ تحليل الوردية'}).click();await page.getByRole('button',{name:'ابدأ تصنيف الأدلة'}).click();await classify(page);await page.getByRole('button',{name:'انتقل إلى الأسئلة التشخيصية'}).click();await assertAccessible(page,'mandatory diagnostics');await answerQuestions(page);await page.getByRole('button',{name:/ابن خريطة/}).click();await assertAccessible(page,'ordinal power');await rankPower(page);await page.getByRole('button',{name:'اكتب استنتاجك'}).click();await assertAccessible(page,'claim evidence conclusion')});
