import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
async function assertAccessible(page,label){const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();expect(results.violations,`${label}: ${results.violations.map(v=>`${v.id}(${v.nodes.length})`).join(', ')}`).toEqual([])}
async function startData(page){await page.goto('/');await page.getByRole('button',{name:'ابدأ المحاكاة'}).click();await page.locator('article.scenario').filter({hasText:'سامر'}).getByRole('button',{name:'اختيار هذه الحالة'}).click()}
async function enterData(page){await startData(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click()}
async function startScenario(page,name){await page.goto('/');await page.getByRole('button',{name:'ابدأ المحاكاة'}).click();await page.locator('article.scenario').filter({hasText:name}).getByRole('button',{name:'اختيار هذه الحالة'}).click();await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click()}
async function firstChoices(page){const samples=page.locator('.sample');for(let i=0;i<await samples.count();i++)await samples.nth(i).locator('button.choice').first().click()}
async function classify(page){const docs=page.locator('.doc').filter({has:page.locator('.sort')});for(let i=0;i<await docs.count();i++)await docs.nth(i).locator('.sort').first().click()}
async function questions(page){const selects=page.locator('select[data-q]');for(let i=0;i<await selects.count();i++)await selects.nth(i).selectOption({index:1})}
async function power(page){for(;;){const slider=page.locator('fieldset.power-card input[type="range"]').first();await slider.evaluate(el=>{el.value='40';el.dispatchEvent(new Event('input',{bubbles:true}))});const next=page.getByRole('button',{name:'المحور التالي'});if(await next.count())await next.click();else break}}
test('landing, scenario, onboarding and work are accessible',async({page})=>{await page.goto('/');await assertAccessible(page,'home');await page.getByRole('button',{name:'ابدأ المحاكاة'}).click();await assertAccessible(page,'scenario');await page.locator('article.scenario').filter({hasText:'سامر'}).getByRole('button',{name:'اختيار هذه الحالة'}).click();await assertAccessible(page,'onboarding');await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await assertAccessible(page,'work')});
test('semantic answer preserves keyboard focus after rerender',async({page},testInfo)=>{test.skip(testInfo.project.name.startsWith('mobile-'),'desktop keyboard focus');await enterData(page);await page.getByRole('button',{name:'قبول',exact:true}).first().click();const region=page.locator('[data-semantic-region="first-0"]'),size=page.locator('[data-semantic-size="first-0"]');await region.selectOption({index:1});await size.selectOption({index:1});await expect(page.locator('[data-semantic-region="first-1"]')).toBeFocused()});
test('no-work access and researcher evidence are accessible',async({page})=>{await enterData(page);await page.getByRole('button',{name:'إنهاء الوردية دون قبول عمل'}).click();await assertAccessible(page,'access no-work');await page.getByRole('button',{name:'ابدأ تحليل الوردية'}).click();await assertAccessible(page,'investigation case');await page.getByRole('button',{name:'ابدأ تصنيف الأدلة'}).click();await assertAccessible(page,'investigation evidence')});
test('full worker and researcher journey stays accessible',async({page})=>{
 await startScenario(page,'ليان');await assertAccessible(page,'work market');
 await page.getByRole('button',{name:'قبول',exact:true}).first().click();await assertAccessible(page,'work task');await firstChoices(page);await page.getByRole('button',{name:'إرسال العمل للمراجعة'}).click();await assertAccessible(page,'work result');
 await page.getByRole('button',{name:'رؤية أثر الأداء على فرص العمل'}).click();await assertAccessible(page,'management ranking');await page.getByRole('button',{name:'رؤية العرض الناتج عن هذا التحديث'}).click();await assertAccessible(page,'management offer');await page.getByRole('button',{name:'أنهي الوردية الآن'}).click();await assertAccessible(page,'management monitor');await page.getByRole('button',{name:'الانتقال إلى المراجعة دون استراحة'}).click();
 await assertAccessible(page,'risk');await page.getByRole('button',{name:'متابعة إلى مراجعة جودة العمل'}).click();await assertAccessible(page,'dispute');const skip=page.getByRole('button',{name:/متابعة إلى التسوية|المتابعة دون اعتراض/});await skip.first().click();
 await assertAccessible(page,'payment');await page.getByRole('button',{name:'إنهاء التسوية ومراجعة الوصول'}).click();await assertAccessible(page,'access full');await page.getByRole('button',{name:'ابدأ تحليل الوردية'}).click();await assertAccessible(page,'investigation case full');await page.getByRole('button',{name:'ابدأ تصنيف الأدلة'}).click();await assertAccessible(page,'investigation evidence full');await classify(page);await page.getByRole('button',{name:'انتقل إلى الأسئلة التشخيصية'}).click();await assertAccessible(page,'investigation questions');await questions(page);await page.getByRole('button',{name:/ابن خريطة/}).click();await assertAccessible(page,'power');await power(page);await page.getByRole('button',{name:'اكتب استنتاجك'}).click();await assertAccessible(page,'conclusion');
 await page.locator('#analysis').fill('توضح وقائع الجولة أن السلطة والعبء لا يتوزعان بالطريقة نفسها، وأن كل استنتاج يجب أن يرتبط بما وقع فعليًا.');const roles=page.locator('select[data-evidence-role]');await roles.nth(0).selectOption('support');if(await roles.count()>1)await roles.nth(1).selectOption('support');await page.getByRole('button',{name:'إظهار النتيجة'}).click();await assertAccessible(page,'result');await page.getByRole('button',{name:'اربط التجربة بالحقوق'}).click();await assertAccessible(page,'rights');
});
