import {test,expect} from '@playwright/test';
async function startDataScenario(page){await page.goto('/');await page.getByRole('button',{name:'ابدأ المحاكاة'}).click();await expect(page).toHaveURL(/\/scenario\/$/);const samer=page.locator('article.scenario').filter({hasText:'سامر'});await samer.getByRole('button',{name:'اختيار هذه الحالة'}).click();await expect(page).toHaveURL(/\/onboarding\/$/)}
test('landing page starts a fictional training simulation',async({page})=>{await page.goto('/');await expect(page).toHaveTitle(/قبل الوردية \| No Boss v3\.0\.2/);await expect(page.getByRole('heading',{name:'No Boss'})).toBeVisible();await expect(page.getByText('عالم المحاكاة خيالي.')).toBeVisible();await page.getByRole('button',{name:'ابدأ المحاكاة'}).click();await expect(page).toHaveURL(/\/scenario\/$/);await expect(page.getByText('محاكاة خيالية:')).toBeVisible()});
test('scenario selection seeds a unique sample plan and onboarding reaches work',async({page})=>{await startDataScenario(page);await expect(page.getByText('سامر · عامل تصنيف بيانات')).toBeVisible();await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await expect(page).toHaveURL(/\/work\/$/);await expect(page.getByText('اختر عرضًا، ارفض عرضًا بعينه، أو أنهِ الوردية دون عمل.')).toBeVisible();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(saved.scenarioKey).toBe('data');expect(saved.sampleSequence).toHaveLength(6);expect(new Set(saved.sampleSequence).size).toBe(6);expect(saved.evidence).toEqual(expect.arrayContaining(['contract','ownTools','multiPlatform']))});
test('market exit is available before any rejection and adds no rejection',async({page})=>{await startDataScenario(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await expect(page.getByRole('button',{name:'إنهاء الوردية دون قبول عمل'})).toBeVisible();await page.getByRole('button',{name:'إنهاء الوردية دون قبول عمل'}).click();await expect(page).toHaveURL(/\/access\/$/);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(saved.noWorkEnding).toBe(true);expect(saved.marketExit).toBe(true);expect(saved.rejections).toBe(0);expect(saved.accountOutcome).toBe('active')});
test('data task keeps a keyboard-accessible annotation path scored through the same geometry',async({page})=>{await startDataScenario(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await page.getByRole('button',{name:'قبول',exact:true}).first().click();const groups=page.locator('fieldset.semantic-region');await expect(groups).toHaveCount(3);for(let i=0;i<3;i++){await groups.nth(i).locator('select.semantic-pos').selectOption({index:1});await groups.nth(i).locator('select.semantic-width').selectOption('medium')}const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(before.workAnswers).toHaveLength(3);expect(before.workAnswers.every(answer=>answer?.source==='semantic'&&answer?.widthId==='medium')).toBe(true);await page.getByRole('button',{name:'إرسال العمل للمراجعة'}).click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(saved.completedTasks).toHaveLength(1);expect(saved.completedTasks[0].sampleIndexes).toEqual(before.currentTaskSampleIndexes);expect(saved.completedTasks[0].reviewMetrics).toHaveLength(3);expect(Number.isFinite(saved.completedTasks[0].score)).toBe(true)});
test('back from onboarding restores scenario selection',async({page})=>{await startDataScenario(page);await page.getByRole('button',{name:'رجوع'}).click();await expect(page).toHaveURL(/\/scenario\/$/);await expect(page.getByText('اختر حالة عمل واحدة لتبدأ وردية جديدة.')).toBeVisible()});
test('home resume returns to current active stage',async({page})=>{await startDataScenario(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'العودة إلى الصفحة الرئيسية'}).click();await expect(page).toHaveURL(/\/$/);await page.getByRole('button',{name:'متابعة الجلسة'}).click();await expect(page).toHaveURL(/\/work\/$/)});
test('reload preserves current work route',async({page})=>{await startDataScenario(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await page.reload();await expect(page).toHaveURL(/\/work\/$/);await expect(page.getByText('اختر عرضًا، ارفض عرضًا بعينه، أو أنهِ الوردية دون عمل.')).toBeVisible()});
test('direct protected route without state returns home',async({page})=>{await page.goto('/payment/');await expect(page).toHaveURL(/\/$/);await expect(page.getByRole('heading',{name:'No Boss'})).toBeVisible()});
test('mobile shell keeps current task visible before expanded summary',async({page},testInfo)=>{test.skip(testInfo.project.name!=='mobile-chromium','mobile-only assertion');await startDataScenario(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await expect(page.locator('.compact-stats')).toBeVisible();await expect(page.locator('#summaryDetails')).not.toHaveClass(/open/);const task=page.locator('.task-now').first();await expect(task).toBeVisible();const box=await task.boundingBox();expect(box?.y??9999).toBeLessThan(844);await expect(page.getByRole('button',{name:'رجوع'})).toBeVisible();await expect(page.getByRole('button',{name:'بدء من جديد'})).toBeVisible()});
