import {test,expect} from '@playwright/test';
async function startData(page){await page.goto('/');await page.getByRole('button',{name:'ابدأ المحاكاة'}).click();await page.locator('article.scenario').filter({hasText:'سامر'}).getByRole('button',{name:'اختيار هذه الحالة'}).click()}
async function enterDataWork(page){await startData(page);await page.getByRole('button',{name:'أوافق وأدخل No Boss'}).click();await expect(page).toHaveURL(/\/work\/$/)}
const semanticChoice={0:['leftCenter','standard'],1:['rightCenter','standard'],2:['center','standard'],3:['left','short'],4:['right','short'],5:['center','wide']};

test('landing page identifies v3.2.0 fictional simulation',async({page})=>{await page.goto('/');await expect(page).toHaveTitle(/No Boss v3\.2\.0/);await expect(page.getByText('عالم المحاكاة خيالي.')).toBeVisible()});

test('market exit before rejection remains a valid zero-work path',async({page})=>{await enterDataWork(page);await page.getByRole('button',{name:'إنهاء الوردية دون قبول عمل'}).click();await expect(page).toHaveURL(/\/access\/$/);const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(s.noWorkEnding).toBe(true);expect(s.rejections).toBe(0);expect(s.accountOutcome).toBe('active');expect(s.marketTime).toBeGreaterThan(0)});

test('nonvisual data mode requires both location and size and remains fully usable',async({page})=>{await enterDataWork(page);await page.getByRole('button',{name:'قبول',exact:true}).first().click();await expect(page.locator('[role="application"]')).toHaveCount(0);const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));for(let i=0;i<state.currentTaskSampleIndexes.length;i++){const [region,size]=semanticChoice[state.currentTaskSampleIndexes[i]];await page.locator(`[data-semantic-region="${i}"]`).selectOption(region);await page.locator(`[data-semantic-size="${i}"]`).selectOption(size)}const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(before.workAnswers).toHaveLength(state.currentTaskSampleIndexes.length);expect(before.workAnswers.every(a=>a?.source==='semantic'&&a?.regionId&&a?.sizeId)).toBe(true);await page.getByRole('button',{name:'إرسال العمل للمراجعة'}).click();const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('no_boss_state')));expect(after.completedTasks[0].score).toBe(100)});

test('reload and home resume preserve active work route',async({page})=>{await enterDataWork(page);await page.reload();await expect(page).toHaveURL(/\/work\/$/);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'العودة إلى الصفحة الرئيسية'}).click();await page.getByRole('button',{name:'متابعة الجلسة'}).click();await expect(page).toHaveURL(/\/work\/$/)});

test('direct protected route without state returns home',async({page})=>{await page.goto('/payment/');await expect(page).toHaveURL(/\/$/)});

test('mobile shell keeps task reachable without horizontal overflow',async({page},testInfo)=>{test.skip(!testInfo.project.name.startsWith('mobile-'),'mobile only');await enterDataWork(page);const integrity=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(integrity.scroll).toBeLessThanOrEqual(integrity.client+2);const task=page.locator('.task-now').first();await expect(task).toBeVisible();const box=await task.boundingBox();expect(box?.y??9999).toBeLessThan(900)});