import assert from 'node:assert/strict';
import {APP_VERSION,RESULT_VERSION,SCORE_MODEL_VERSION,ECONOMY_MODEL_VERSION} from '../assets/js/core/config.js';
import {powerAxisCredit,leaders,secondTier} from '../assets/js/core/power-scoring.js';
assert.equal(APP_VERSION,'3.8.0');
assert.equal(RESULT_VERSION,'No Boss v3.8.0');
assert.equal(SCORE_MODEL_VERSION,'8');
assert.equal(ECONOMY_MODEL_VERSION,'3');
globalThis.location={pathname:'/taskbridge-game/work/index.html'};
const {projectBase,pageFromPath,href,pageForStage,stageForPage,isPublicPage,isResearcherPage}=await import('../assets/js/core/routes.js');
assert.equal(pageFromPath(),'work');assert.equal(projectBase(),'/taskbridge-game/');assert.equal(href('management'),'/taskbridge-game/management/');assert.equal(pageForStage(0),'scenario');assert.equal(pageForStage(11),'result');assert.equal(stageForPage('rights'),11);assert.equal(isPublicPage('home'),true);assert.equal(isResearcherPage('investigation'),true);
const ref={primary:['platform'],secondary:['client']};assert.deepEqual(leaders({worker:10,platform:60,client:30}),['platform']);assert.deepEqual(secondTier({worker:10,platform:60,client:30}),['client']);assert.equal(powerAxisCredit({worker:10,platform:60,client:30},ref),1);assert.equal(powerAxisCredit({worker:30,platform:60,client:10},ref),.7);assert.equal(powerAxisCredit({worker:0,platform:50,client:50},{primary:['platform','client'],secondary:[]}),1);
const localStore=new Map(),sessionStore=new Map();globalThis.localStorage={getItem:k=>localStore.has(k)?localStore.get(k):null,setItem:(k,v)=>localStore.set(k,String(v)),removeItem:k=>localStore.delete(k)};globalThis.sessionStorage={getItem:k=>sessionStore.has(k)?sessionStore.get(k):null,setItem:(k,v)=>sessionStore.set(k,String(v)),removeItem:k=>sessionStore.delete(k)};
const stateModule=await import('../assets/js/core/state.js');const {getState,commit,freshState,normalizeState,STATE_SCHEMA_VERSION,currentBackLabel}=stateModule;
assert.equal(STATE_SCHEMA_VERSION,9);assert.deepEqual(getState(),freshState());
for(const key of ['completedTasks','sampleSequence','marketTime','reviewTaskId','conclusionDualEvidence','contractDeclineEnding','termsDeclinedBefore','riskSeed','powerConfirmed','baselineAcceptedOffers','baselineOfferDecisions','conclusionAuthority','conclusionBurden'])assert.ok(key in getState());
for(const removed of ['marketExit','powerDraft','powerEdited','powerTouched','qualityAfterFirstTask','reviewTaskScore','realFinishedAt','initialStress','firstTaskStress','secondTaskScore','disputeSeverity','disputedTaskPay'])assert.equal(removed in getState(),false,`legacy field ${removed} should be removed`);
for(const [stage,currentPage] of [[9,'power'],[10,'conclusion'],[11,'result']]){
 const migrated=normalizeState({schemaVersion:8,storageRevision:2,currentPage,stage,scenarioKey:'data',baselineAcceptedOffers:18,baselineOfferDecisions:22,acceptedOffers:19,offerDecisions:23,acceptance:83,resultData:{score:99},checkpoints:[{page:'old'}],power:{price:{worker:8,platform:57,client:30}},powerConfirmed:['price'],conclusionAuthority:'platform',conclusionBurden:'worker'});
 assert.equal(migrated.schemaVersion,STATE_SCHEMA_VERSION);assert.equal(migrated.stage,9);assert.equal(migrated.currentPage,'power');assert.equal(migrated.resultData,null);assert.equal(migrated.checkpoints.length,0);assert.deepEqual(migrated.powerConfirmed,[]);assert.equal(migrated.conclusionAuthority,null);assert.equal(migrated.conclusionBurden,null);assert.equal(migrated.baselineOfferDecisions,22);assert.equal(migrated.offerDecisions,23);
}
const older=normalizeState({schemaVersion:7,currentPage:'work',stage:2,scenarioKey:'data',acceptedOffers:1,offerDecisions:2,acceptance:50,powerTouched:['price'],marketExit:true});assert.equal(older.baselineAcceptedOffers,18);assert.equal(older.baselineOfferDecisions,22);assert.equal(older.acceptedOffers,19);assert.equal(older.offerDecisions,24);assert.equal(older.acceptance,79);assert.equal('marketExit' in older,false);assert.equal('powerTouched' in older,false);
const paymentMigrated=normalizeState({schemaVersion:8,currentPage:'payment',stage:6,scenarioKey:'data',payment:{hold:.2,net:.5}}).payment;assert.equal(paymentMigrated.availableNet,.5);assert.equal(paymentMigrated.heldBalance,.2);assert.equal(paymentMigrated.economicPosition,.7);
commit({changes:{status:'اختبار'},checkpointLabel:'التراجع عن اختبار'});assert.equal(currentBackLabel(),'التراجع عن اختبار');commit({changes:{reviewTaskScore:99,unknownLegacy:true,powerTouched:['price']}});assert.equal('reviewTaskScore' in getState(),false);assert.equal('unknownLegacy' in getState(),false);assert.equal('powerTouched' in getState(),false);
const storage=await import('../assets/js/core/storage.js');localStore.set('no_boss_results','{}');assert.deepEqual(storage.savedResults(),[]);assert.equal(storage.archiveResult({scenarioName:'بلا معرف'}),false);assert.equal(storage.archiveResult({runId:'compact',scenarioKey:'data',scenarioName:'سامي',runPath:'no-work',score:88,netEconomic:-.4,breakTaken:null,appVersion:APP_VERSION,scoreModelVersion:SCORE_MODEL_VERSION,economyModelVersion:ECONOMY_MODEL_VERSION}),true);const compact=JSON.parse(localStore.get('no_boss_results')).find(r=>r.runId==='compact');assert.equal(compact.scoreModelVersion,'8');assert.equal(compact.economyModelVersion,'3');assert.equal(compact.breakTaken,null);
console.log('No Boss regression checks passed');
