import assert from 'node:assert/strict';
import {APP_VERSION,RESULT_VERSION,SCORE_MODEL_VERSION} from '../assets/js/core/config.js';
import {powerAxisCredit,leaders,topGroup} from '../assets/js/core/power-scoring.js';

assert.equal(APP_VERSION,'3.3.0');
assert.equal(RESULT_VERSION,'No Boss v3.3.0');
assert.equal(SCORE_MODEL_VERSION,'3');
globalThis.location={pathname:'/taskbridge-game/work/index.html'};
const {projectBase,pageFromPath,href,pageForStage,stageForPage,isPublicPage,isResearcherPage}=await import('../assets/js/core/routes.js');
assert.equal(pageFromPath(),'work');assert.equal(projectBase(),'/taskbridge-game/');assert.equal(href('management'),'/taskbridge-game/management/');assert.equal(pageForStage(0),'scenario');assert.equal(pageForStage(11),'result');assert.equal(stageForPage('rights'),11);assert.equal(isPublicPage('home'),true);assert.equal(isResearcherPage('investigation'),true);
const equal={worker:34,platform:33,client:33},target={worker:8,platform:60,client:32};assert.deepEqual(leaders(equal),['worker']);assert.deepEqual(topGroup(target,2),['platform','client']);assert.equal(powerAxisCredit(target,target),1);assert.ok(powerAxisCredit({worker:70,platform:20,client:10},target)<.5);assert.equal(powerAxisCredit({worker:0,platform:90,client:10},target),1,'rank-equivalent maps should not be punished for hidden percentages');
const localStore=new Map(),sessionStore=new Map();const localStorageObject={getItem:k=>localStore.has(k)?localStore.get(k):null,setItem:(k,v)=>localStore.set(k,String(v)),removeItem:k=>localStore.delete(k)};const sessionStorageObject={getItem:k=>sessionStore.has(k)?sessionStore.get(k):null,setItem:(k,v)=>sessionStore.set(k,String(v)),removeItem:k=>sessionStore.delete(k)};globalThis.localStorage=localStorageObject;globalThis.sessionStorage=sessionStorageObject;
const stateModule=await import('../assets/js/core/state.js');const {getState,setState,commit,freshState,normalizeState,STATE_SCHEMA_VERSION}=stateModule;assert.deepEqual(getState(),freshState());for(const key of ['completedTasks','sampleSequence','marketTime','reviewTaskId','conclusionDualEvidence','contractDeclineEnding','riskSeed','powerTouched'])assert.ok(key in getState());for(const removed of ['marketExit','powerDraft','powerEdited','qualityAfterFirstTask','reviewTaskScore','realFinishedAt'])assert.equal(removed in getState(),false,`legacy field ${removed} should be removed`);
const migrated=normalizeState({schemaVersion:3,storageRevision:2,currentPage:'work',stage:2,scenarioKey:'data',power:{price:{worker:8,platform:57,client:30,mediator:5}},marketExit:true,powerDraft:{}});assert.equal(migrated.schemaVersion,STATE_SCHEMA_VERSION);assert.equal('marketExit' in migrated,false);assert.equal('mediator' in migrated.power.price,false);assert.equal(Object.values(migrated.power.price).reduce((a,b)=>a+b,0),100);
const before=getState().storageRevision;commit({changes:{status:'اختبار'},evidence:['contract'],log:{title:'اختبار',text:'دفعة واحدة'}});assert.equal(getState().storageRevision,before+1);
const storage=await import('../assets/js/core/storage.js');localStore.set('no_boss_results','{}');assert.deepEqual(storage.savedResults(),[]);assert.equal(storage.archiveResult({scenarioName:'بلا معرف'}),false);assert.equal(storage.archiveResult({runId:'compact',scenarioName:'سامي',runPath:'no-work',score:88,netEconomic:-.4,appVersion:APP_VERSION,scoreModelVersion:SCORE_MODEL_VERSION}),true);const compact=JSON.parse(localStore.get('no_boss_results')).find(r=>r.runId==='compact');assert.equal(compact.runPath,'no-work');assert.equal(compact.scoreModelVersion,'3');assert.ok(!('answers' in compact));
console.log('No Boss regression checks passed');
