import assert from 'node:assert/strict';
import {APP_VERSION,RESULT_VERSION,SCORE_MODEL_VERSION} from '../assets/js/core/config.js';
import {powerAxisCredit,leaders,topGroup,distributionProximity} from '../assets/js/core/power-scoring.js';

assert.equal(APP_VERSION,'3.3.0');
assert.equal(RESULT_VERSION,'No Boss v3.3.0');
assert.equal(SCORE_MODEL_VERSION,'2');

globalThis.location={pathname:'/taskbridge-game/work/index.html'};
const {projectBase,pageFromPath,href,pageForStage,stageForPage,isPublicPage,isResearcherPage}=await import('../assets/js/core/routes.js');
assert.equal(pageFromPath(),'work');assert.equal(projectBase(),'/taskbridge-game/');assert.equal(href('management'),'/taskbridge-game/management/');assert.equal(pageForStage(0),'scenario');assert.equal(pageForStage(11),'result');assert.equal(stageForPage('rights'),11);assert.equal(isPublicPage('home'),true);assert.equal(isPublicPage('scenario'),true);assert.equal(isPublicPage('work'),false);assert.equal(isResearcherPage('investigation'),true);assert.equal(isResearcherPage('work'),false);location.pathname='/taskbridge-game/index.html';assert.equal(pageFromPath(),'home');assert.equal(projectBase(),'/taskbridge-game/');

const equal={worker:25,platform:25,client:25,mediator:25};
const target={worker:8,platform:57,client:30,mediator:5};
assert.deepEqual(leaders(equal),['worker','platform','client','mediator']);assert.deepEqual(topGroup(equal,2),['worker','platform','client','mediator']);assert.equal(powerAxisCredit(target,target),1);assert.equal(distributionProximity(target,target),1);assert.ok(powerAxisCredit(equal,target)<.5,'untouched equal distribution must remain substantially below the reference');assert.ok(powerAxisCredit({worker:60,platform:10,client:20,mediator:10},target)<.4,'wrong leader should not receive majority credit');assert.equal(powerAxisCredit({worker:0,platform:95,client:5,mediator:0},target),1,'same primary and strongest group must not lose credit for hidden percentage distance');

const localStore=new Map(),sessionStore=new Map();
const localStorageObject={getItem:key=>localStore.has(key)?localStore.get(key):null,setItem:(key,value)=>localStore.set(key,String(value)),removeItem:key=>localStore.delete(key)};
const sessionStorageObject={getItem:key=>sessionStore.has(key)?sessionStore.get(key):null,setItem:(key,value)=>sessionStore.set(key,String(value)),removeItem:key=>sessionStore.delete(key)};
globalThis.localStorage=localStorageObject;globalThis.sessionStorage=sessionStorageObject;

const stateModule=await import('../assets/js/core/state.js');
const {getState,setState,commit,patchTransient,flushState,consumeCheckpointTo,resumePage,enterPage,undoCheckpoint,freshState,normalizeState,STATE_SCHEMA_VERSION}=stateModule;
assert.deepEqual(getState(),freshState(),'empty storage must start from a fresh state');
assert.equal(STATE_SCHEMA_VERSION,4);
for(const key of ['completedTasks','sampleSequence','sampleCursor','marketExit','marketTime','reviewTaskId','opportunityRankingDecision','conclusionCounterEvidence','conclusionDualEvidence','contractDeclineEnding','riskSeed','storageUpdatedAt','appVersion','scoreModelVersion'])assert.ok(key in getState(),`fresh state missing ${key}`);
for(const removed of ['powerDraft','reviewTaskScore'])assert.equal(removed in getState(),false,`removed legacy state field still exists: ${removed}`);
const legacy=normalizeState({schemaVersion:3,appVersion:'3.2.0',scoreModelVersion:'2',storageRevision:2,currentPage:'result',stage:11,scenarioKey:'data',resultData:{score:99},accessDecision:{outcome:'suspended'},payment:{net:5}});assert.deepEqual(legacy,freshState(),'incompatible live state must be discarded instead of mixing derived results across versions');
const compatible=normalizeState({...freshState(),appVersion:'3.3.99',storageRevision:2,storageUpdatedAt:10,currentPage:'work',stage:2,scenarioKey:'data',completedTasks:null,evidence:null,conclusionDualEvidence:null});assert.equal(compatible.schemaVersion,STATE_SCHEMA_VERSION);assert.equal(compatible.scenarioKey,'data','app patch version alone must not invalidate a schema-compatible live state');assert.equal(compatible.appVersion,APP_VERSION);assert.deepEqual(compatible.completedTasks,[]);assert.deepEqual(compatible.evidence,[]);assert.deepEqual(compatible.conclusionDualEvidence,[]);
setState({...getState(),scenarioKey:'data',stage:2,currentPage:'work'});const beforeTransient=getState().storageRevision;patchTransient({analysisText:'مسودة غير محفوظة بعد'});assert.equal(getState().analysisText,'مسودة غير محفوظة بعد');assert.equal(getState().storageRevision,beforeTransient,'transient input must not persist on every keystroke');flushState();assert.equal(getState().storageRevision,beforeTransient+1,'explicit flush must persist transient input once');
const beforeCommitRevision=getState().storageRevision;commit({changes:{status:'اختبار دفعة واحدة'},evidence:['contract','ownTools'],log:{title:'اختبار',text:'عملية واحدة'}});assert.equal(getState().storageRevision,beforeCommitRevision+1,'a batched commit must persist once');assert.deepEqual(getState().evidence,['contract','ownTools']);assert.equal(getState().log.at(-1)?.title,'اختبار');
setState({...getState(),selectedRights:['privacy'],currentPage:'rights',stage:11,checkpoints:[{page:'result',snapshot:{}}]});assert.equal(consumeCheckpointTo('result'),'result');assert.deepEqual(getState().selectedRights,['privacy'],'returning from Rights must keep current result state');
setState({...getState(),scenarioKey:'data',stage:1,currentPage:'scenario',checkpoints:[]});const beforeEnterRevision=getState().storageRevision;enterPage('onboarding');assert.equal(getState().storageRevision,beforeEnterRevision+1,'entering a new page must persist checkpoint and current page once');assert.equal(getState().currentPage,'onboarding');assert.equal(getState().checkpoints.at(-1)?.page,'scenario');assert.deepEqual(Object.keys(getState().checkpoints.at(-1)).sort(),['page','snapshot']);const samePageRevision=getState().storageRevision;enterPage('onboarding');assert.equal(getState().storageRevision,samePageRevision);assert.equal(undoCheckpoint(),'scenario');assert.equal(resumePage({scenarioKey:'data',stage:1,currentPage:'scenario'}),'onboarding');assert.equal(resumePage({scenarioKey:'data',stage:11,currentPage:'rights'}),'rights');assert.equal(resumePage({scenarioKey:'data',stage:5,currentPage:'work'}),'dispute');

const storage=await import('../assets/js/core/storage.js');
localStore.set('no_boss_results','{}');assert.deepEqual(storage.savedResults(),[],'malformed result stores must not crash');
const baseState={...freshState(),scenarioKey:'ai',stage:2,currentPage:'work'};
localStore.set('no_boss_state',JSON.stringify({...baseState,storageRevision:8,storageUpdatedAt:100,storageWriterId:'writer-a',scenarioKey:'ai'}));sessionStore.set('no_boss_state',JSON.stringify({...baseState,storageRevision:8,storageUpdatedAt:200,storageWriterId:'writer-b',scenarioKey:'data'}));assert.equal(storage.loadState().scenarioKey,'data','equal revisions must prefer the later logical timestamp');assert.equal(storage.stateStorageMode(),'session');
localStore.set('no_boss_state',JSON.stringify({...baseState,storageRevision:9,storageUpdatedAt:300,storageWriterId:'writer-z',scenarioKey:'translation'}));sessionStore.set('no_boss_state',JSON.stringify({...baseState,storageRevision:9,storageUpdatedAt:300,storageWriterId:'writer-a',scenarioKey:'data'}));assert.equal(storage.loadState().scenarioKey,'translation','equal revision and timestamp must have a deterministic writer-id tie break');
localStore.set('no_boss_state',JSON.stringify({...baseState,schemaVersion:3,appVersion:'3.2.0',storageRevision:20,storageUpdatedAt:500,storageWriterId:'old-tab',scenarioKey:'moderation'}));sessionStore.set('no_boss_state',JSON.stringify({...baseState,storageRevision:19,storageUpdatedAt:450,storageWriterId:'current-tab',scenarioKey:'data'}));const pruned=storage.pruneStateCandidates(value=>Number(value?.schemaVersion)===STATE_SCHEMA_VERSION&&String(value?.scoreModelVersion)===SCORE_MODEL_VERSION);assert.equal(pruned,1,'only the incompatible storage candidate should be removed');assert.equal(localStore.has('no_boss_state'),false);assert.equal(storage.loadState().scenarioKey,'data','a compatible candidate in another storage area must survive pruning');
const originalLocalSet=localStorageObject.setItem;localStorageObject.setItem=()=>{throw new Error('quota')};const fallback=storage.saveState({...baseState,storageRevision:21,storageUpdatedAt:600,storageWriterId:'guarded',scenarioKey:'moderation'});assert.equal(fallback.status,'session');assert.equal(storage.loadState().currentPage,'work');assert.equal(storage.archiveResult({runId:'x'}),false);localStorageObject.setItem=originalLocalSet;
assert.equal(storage.archiveResult({scenarioName:'بلا معرف',score:1}),false);const archived=storage.archiveResult({runId:'compact',scenarioName:'سامي',score:88,outcome:'warning',simMinutes:42,netEconomic:3.25,finalStress:51,breakTaken:true,appVersion:APP_VERSION,scoreModelVersion:SCORE_MODEL_VERSION,analysis:'لا حاجة للاحتفاظ بهذا النص',answers:{price:'المنصة'},power:{price:{worker:1,platform:99}},createdAt:'2026-08-21T12:00:00.000Z',scenario:'data'});assert.equal(archived,true);const storedArchive=JSON.parse(localStore.get('no_boss_results')),compact=storedArchive.find(result=>result.runId==='compact');assert.ok(compact);assert.deepEqual(Object.keys(compact).sort(),['appVersion','breakTaken','finalStress','netEconomic','outcome','runId','scenarioName','score','scoreModelVersion','simMinutes'].sort());assert.equal(compact.appVersion,APP_VERSION);assert.equal(compact.scoreModelVersion,SCORE_MODEL_VERSION);assert.equal(storage.clearResults(),true);assert.deepEqual(storage.savedResults(),[],'archive deletion must remove all locally saved results');
Object.defineProperty(globalThis,'localStorage',{configurable:true,get(){throw new Error('blocked')}});sessionStore.clear();const guarded=storage.saveState({...baseState,storageRevision:22,storageUpdatedAt:700,storageWriterId:'guarded',scenarioKey:'moderation',stage:3,currentPage:'management'});assert.equal(guarded.status,'session');assert.equal(storage.loadState().currentPage,'management');Object.defineProperty(globalThis,'localStorage',{configurable:true,writable:true,value:localStorageObject});
console.log('No Boss regression checks passed');
