import assert from 'node:assert/strict';
import {scenarios} from '../assets/js/data/scenarios.js';
import {axes,parties} from '../assets/js/data/parties.js';
import {authorityModel,authorityLeaders,authorityReference,authorityReferenceForState} from '../assets/js/data/authority-model.js';
import {powerAxisCredit} from '../assets/js/core/power-scoring.js';
import {buildPaymentSettlement,operatingCost} from '../assets/js/domain/payment.js';
import {assessAccessDecision} from '../assets/js/domain/access.js';
import {evidenceFor} from '../assets/js/domain/evidence.js';
import {questionsForState,acceptedQuestionAnswer,diagnosticFeedback} from '../assets/js/domain/questions.js';
import {analysisAxes,evidenceDimensions,powerMapComplete,scoreAnalysis} from '../assets/js/domain/analysis.js';
import {intersectionOverUnion,scoreWork,firstTaskOutcome,semanticDataAnswer,createSampleSequence,samplePoolSize,qualityAfterTask,answerCredit,acceptanceRate} from '../assets/js/domain/work.js';
import {dataTargetForScene} from '../assets/js/data/data-scenes.js';
import {samples} from '../assets/js/data/samples.js';
import {computeManagedAccess,baselineAcceptanceRate,buildSecondOffer,premiumSampleCount,completeSecondTask,monitorDecision,BREAK_MINUTES,BREAK_STRESS_REDUCTION} from '../assets/js/domain/management.js';
import {reviewAppeal,selectReviewTask,reviewProfile,disputeConsequences,applyDisputeOutcome,availableAppealGrounds,appealCostChanges} from '../assets/js/domain/dispute.js';
import {riskTransition} from '../assets/js/domain/risk.js';
const close=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
assert.deepEqual(parties,['worker','platform','client']);
for(const [type,sc] of Object.entries(scenarios)){
 assert.ok(sc.accessPolicy.premiumAt>sc.initial.access);
 assert.ok(sc.offerHistory.decisions>=20);
 assert.ok(sc.offerHistory.accepted>0&&sc.offerHistory.accepted<sc.offerHistory.decisions);
 const baseline=acceptanceRate(sc.offerHistory.accepted,sc.offerHistory.decisions);
 const baseState={baselineAcceptedOffers:sc.offerHistory.accepted,baselineOfferDecisions:sc.offerHistory.decisions};
 const neutral=computeManagedAccess(sc,{...baseState,completedTasks:[{score:85}],workScore:85,acceptance:baseline});
 assert.equal(neutral,sc.initial.access,`${type} baseline must not be a penalty`);
 assert.equal(baselineAcceptanceRate(baseState),baseline);
 const acceptedRate=acceptanceRate(sc.offerHistory.accepted+1,sc.offerHistory.decisions+1);
 const excellentAccess=computeManagedAccess(sc,{...baseState,completedTasks:[{score:100}],workScore:100,acceptance:acceptedRate});
 const premium=buildSecondOffer(sc,excellentAccess);
 assert.ok(excellentAccess>=sc.accessPolicy.premiumAt,`${type} perfect first task should make premium reachable from real history`);
 assert.equal(premium.premium,true);
 assert.equal(premium.sampleCount,premiumSampleCount(sc));
 const rejectedRate=acceptanceRate(sc.offerHistory.accepted,sc.offerHistory.decisions+1);
 const rejectedAccess=computeManagedAccess(sc,{...baseState,completedTasks:[{score:85}],workScore:85,acceptance:rejectedRate});
 assert.ok(rejectedAccess<sc.initial.access,`${type} one rejection should visibly reduce ranking`);
 assert.ok(rejectedAccess>=sc.initial.access-3,`${type} one rejection should not collapse ranking`);
 const seq=createSampleSequence(type,1234);assert.equal(new Set(seq).size,seq.length);assert.equal(seq.length,samplePoolSize(type));assert.ok(seq.length>=3+premiumSampleCount(sc));
}
assert.equal(answerCredit(samples.translation[1],'B'),1);assert.equal(answerCredit(samples.translation[2],'A'),1);assert.equal(answerCredit(samples.translation[0],'B'),0);
assert.deepEqual(authorityReferenceForState('data','termination',{contractDeclineEnding:true}),{primary:['platform'],secondary:[]});assert.deepEqual(authorityReferenceForState('translation','risk',{noWorkEnding:true}),{primary:['worker'],secondary:[]});assert.deepEqual(authorityReferenceForState('ai','termination',{noWorkEnding:true}),{primary:['platform'],secondary:[]});
for(const [type,model] of Object.entries(authorityModel))for(const axis of Object.keys(model)){const ref=authorityReference(type,axis);assert.ok(ref.primary.length>=1);assert.ok(ref.primary.every(p=>parties.includes(p)));assert.ok(ref.secondary.every(p=>parties.includes(p)));assert.deepEqual(authorityLeaders(type,axis),parties.filter(p=>ref.primary.includes(p)))}
assert.equal(powerAxisCredit({worker:10,platform:60,client:30},authorityReference('data','price')),1);assert.deepEqual(analysisAxes({noWorkEnding:true}).map(a=>a.id),['price','allocation','risk','termination']);assert.deepEqual(evidenceDimensions({noWorkEnding:true}),['contract','price','allocation','burden','access']);assert.equal(evidenceFor('payment',scenarios.data,{}).scoreable,false);assert.equal(evidenceFor('ownTools',scenarios.data,{}).preferredKind,'burden');
const fullQuestions=questionsForState({scenarioKey:'data'}),noWorkQuestions=questionsForState({scenarioKey:'data',noWorkEnding:true}),contractQuestions=questionsForState({scenarioKey:'data',contractDeclineEnding:true});assert.equal(fullQuestions.length,5);assert.equal(noWorkQuestions[2].id,'noWorkBoundary');assert.equal(contractQuestions.length,1);assert.equal(acceptedQuestionAnswer(fullQuestions[0],fullQuestions[0].reference[0]),true);assert.equal(diagnosticFeedback(fullQuestions[0],fullQuestions[0].reference[0]).correct,true);
const noWorkPayment=buildPaymentSettlement(scenarios.data,{grossWorker:0,clientPaid:0,hold:0});assert.equal(noWorkPayment.mediator,0);assert.equal(noWorkPayment.transfer,0);close(noWorkPayment.availableNet,-operatingCost(scenarios.data));close(noWorkPayment.economicPosition,noWorkPayment.availableNet);assert.equal(assessAccessDecision(scenarios.data,{noWorkEnding:true,rejections:2}).outcome,'warning');
const target0=dataTargetForScene(0);close(intersectionOverUnion(target0,target0),1);const semanticAnswers=[semanticDataAnswer(0,'leftCenter','standard'),semanticDataAnswer(1,'rightCenter','standard'),semanticDataAnswer(2,'center','standard')];assert.equal(scoreWork(scenarios.data,semanticAnswers,{sampleIndexes:[0,1,2]}),100);assert.equal(qualityAfterTask(90,60),80);
const firstState={sampleSequence:[0,1,2,3,4,5],sampleCursor:0,currentTaskSampleIndexes:[0,1,2],completedTasks:[],workAnswers:semanticAnswers,quality:91,selectedJob:{id:'core',title:'مهمة',duration:12,pay:2.1,clientValue:5.8,stress:10},stress:24,time:0,paidTime:0,grossWorker:0,clientPaid:0};const firstTask=firstTaskOutcome(scenarios.data,firstState);assert.equal(firstTask.score,100);
const secondBase={...firstState,...firstTask.changes,stress:95,secondOffer:{id:'second-premium',title:'دفعة مميزة',pay:3.85,duration:18,clientValue:8,premium:true,sampleCount:3,stress:16},offerDecisionResult:{accepted:true},currentTaskSampleIndexes:[3,4,5],secondTaskAnswers:[semanticDataAnswer(3,'left','short'),semanticDataAnswer(4,'right','short'),semanticDataAnswer(5,'center','wide')]};const second=completeSecondTask(scenarios.data,secondBase);assert.equal(second.changes.stress,100);assert.equal(second.stressDelta,5);assert.equal(monitorDecision({stress:42},true).stressAfter,42-BREAK_STRESS_REDUCTION);assert.equal(BREAK_MINUTES,3);
let technicalRisk=null;for(let seed=1;seed<500&&!technicalRisk;seed++){const base={riskSeed:seed,time:12,extraWorkTime:0,stress:30,riskEvent:null,completedTasks:[{id:'task-1',score:90,sampleIndexes:[0],technicalIssueSampleIndexes:[]},{id:'task-2',score:80,sampleIndexes:[1,2],technicalIssueSampleIndexes:[]}]};const out=riskTransition(scenarios.data,base);if(out.event.occurred)technicalRisk=out}assert.ok(technicalRisk);assert.equal(technicalRisk.event.affectedTaskId,'task-2');assert.equal(technicalRisk.event.affectedSampleIndex,2);assert.deepEqual(technicalRisk.changes.completedTasks[1].technicalIssueSampleIndexes,[2]);
const technicalAnswer={x:0,y:0,w:.05,h:.05,source:'visual'},reviewTask={id:'task-2',score:55,pay:3.85,answers:[technicalAnswer],sampleIndexes:[0],technicalIssue:true,technicalIssueSampleIndexes:[0]};const reviewState={completedTasks:[reviewTask],reviewTaskId:'task-2',initialReviewSeverity:2,appealGround:'technical'};assert.ok(availableAppealGrounds(scenarios.data,reviewState).technical);assert.equal(reviewAppeal(scenarios.data,reviewState).accepted,true);const unrelated={...reviewTask,technicalIssueSampleIndexes:[5]};assert.equal(availableAppealGrounds(scenarios.data,{...reviewState,completedTasks:[unrelated]}).technical,undefined);
const unrelatedMixed={id:'task-2',score:30,pay:3.85,answers:[technicalAnswer,technicalAnswer,technicalAnswer],sampleIndexes:[0,1,2],technicalIssueSampleIndexes:[0]};const mixedState={completedTasks:[unrelatedMixed],reviewTaskId:'task-2',initialReviewSeverity:2,appealGround:'technical'};assert.equal(reviewAppeal(scenarios.data,mixedState).accepted,false,'technical issue on one sample must not rescue multiple unrelated hard errors');
const translationTask={id:'task-1',score:60,pay:3,answers:['B'],sampleIndexes:[7]};const translationState={completedTasks:[translationTask],reviewTaskId:'task-1',initialReviewSeverity:1,appealGround:'guideline'};assert.equal(reviewProfile(scenarios.translation,translationTask).groundCounts.guideline,1);assert.ok(availableAppealGrounds(scenarios.translation,translationState).guideline);assert.equal(reviewAppeal(scenarios.translation,translationState).accepted,true);assert.equal(reviewAppeal(scenarios.translation,{...translationState,appealGround:'context'}).accepted,false);
const hardOnly={id:'task-1',score:30,pay:3,answers:['B'],sampleIndexes:[0]};assert.deepEqual(availableAppealGrounds(scenarios.translation,{completedTasks:[hardOnly],reviewTaskId:'task-1'}),{});
assert.equal(appealCostChanges({stress:99,time:0,extraWorkTime:0}).appealCost.stress,1);const major=disputeConsequences(reviewState,2);close(major.hold,.693);assert.equal(applyDisputeOutcome({qualityBeforeDispute:80,completedTasks:[{id:'task-1',pay:2}],reviewTaskId:'task-1',initialReviewSeverity:2,finalReviewSeverity:1}).changes.quality,76);
function perfectValues(ref){const out={worker:0,platform:0,client:0};if(ref.primary.length===2){ref.primary.forEach(p=>out[p]=45);parties.filter(p=>!ref.primary.includes(p)).forEach(p=>out[p]=10)}else if(ref.secondary.length===2){out[ref.primary[0]]=50;ref.secondary.forEach(p=>out[p]=25)}else if(ref.secondary.length===1){out[ref.primary[0]]=60;out[ref.secondary[0]]=30;parties.filter(p=>!ref.primary.includes(p)&&!ref.secondary.includes(p)).forEach(p=>out[p]=10)}else{out[ref.primary[0]]=70;parties.filter(p=>p!==ref.primary[0]).forEach(p=>out[p]=15)}return out}
const perfectPower=Object.fromEntries(axes.map(a=>[a.id,perfectValues(authorityReference('data',a.id))]));const perfectEvidence=['contract','ownTools','priceSetting','allocation','monitoring','clientQuality','payment','accessDecision'],perfectSort={contract:'dep',ownTools:'burden',priceSetting:'ctrl',allocation:'ctrl',monitoring:'ctrl',clientQuality:'ctrl',accessDecision:'ctrl'},analysisState={evidence:perfectEvidence,evidenceSort:perfectSort,power:perfectPower,powerConfirmed:axes.map(a=>a.id)};assert.equal(powerMapComplete(analysisState),true);assert.equal(scoreAnalysis(scenarios.data,analysisState).score,100);
const contractPower={...perfectPower,termination:{worker:20,platform:80,client:0}},contractState={contractDeclineEnding:true,evidence:['contract','contractGate'],evidenceSort:{contract:'dep',contractGate:'ctrl'},power:contractPower,powerConfirmed:['termination']};assert.equal(scoreAnalysis(scenarios.data,contractState).powerScore,60);
console.log('No Boss domain checks passed');
