import assert from 'node:assert/strict';
import {scenarios} from '../assets/js/data/scenarios.js';
import {axes,parties} from '../assets/js/data/parties.js';
import {authorityModel,authorityLeaders,authorityReference,authorityReferenceForState} from '../assets/js/data/authority-model.js';
import {powerAxisCredit} from '../assets/js/core/power-scoring.js';
import {buildPaymentSettlement,operatingCost} from '../assets/js/domain/payment.js';
import {assessAccessDecision} from '../assets/js/domain/access.js';
import {evidenceFor} from '../assets/js/domain/evidence.js';
import {questionsForState,acceptedQuestionAnswer,diagnosticFeedback} from '../assets/js/domain/questions.js';
import {analysisAxes,evidenceDimensions,powerMapComplete,scoreAnalysis} from '../assets/js/domain/analysis.js';
import {intersectionOverUnion,scoreWork,firstTaskOutcome,semanticDataAnswer,createSampleSequence,samplePoolSize,qualityAfterTask,answerCredit,acceptanceRate,taskRecord} from '../assets/js/domain/work.js';
import {dataTargetForScene} from '../assets/js/data/data-scenes.js';
import {samples} from '../assets/js/data/samples.js';
import {computeManagedAccess,baselineAcceptanceRate,buildSecondOffer,premiumSampleCount,completeSecondTask,monitorDecision,secondOfferDecision,SECOND_OFFER_DECISION_MINUTES,BREAK_MINUTES,BREAK_STRESS_REDUCTION} from '../assets/js/domain/management.js';
import {reviewAppeal,selectReviewTask,reviewProfile,disputeConsequences,applyDisputeOutcome,availableAppealGrounds,appealCostChanges,counterfactualAppealScore} from '../assets/js/domain/dispute.js';
import {riskTransition} from '../assets/js/domain/risk.js';
import {normalizeClaimKey} from '../assets/js/pages/conclusion.js';
const close=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
assert.deepEqual(parties,['worker','platform','client']);
for(const [type,sc] of Object.entries(scenarios)){
 assert.ok(sc.accessPolicy.premiumAt>sc.initial.access);
 assert.ok(sc.offerHistory.decisions>=20);
 assert.ok(sc.offerHistory.accepted>0&&sc.offerHistory.accepted<sc.offerHistory.decisions);
 const baseline=acceptanceRate(sc.offerHistory.accepted,sc.offerHistory.decisions);
 const baseState={baselineAcceptedOffers:sc.offerHistory.accepted,baselineOfferDecisions:sc.offerHistory.decisions,acceptedOffers:sc.offerHistory.accepted,offerDecisions:sc.offerHistory.decisions,initialQuality:85};
 const neutral=computeManagedAccess(sc,{...baseState,quality:85});
 assert.equal(neutral,sc.initial.access,`${type} quality 85 with baseline acceptance must be neutral`);
 assert.equal(baselineAcceptanceRate(baseState),baseline);
 const excellentAccess=computeManagedAccess(sc,{...baseState,quality:100,acceptedOffers:sc.offerHistory.accepted+1,offerDecisions:sc.offerHistory.decisions+1});
 assert.ok(excellentAccess>neutral,`${type} higher cumulative quality must improve ranking`);
 const premium=buildSecondOffer(sc,Math.max(sc.accessPolicy.premiumAt,excellentAccess));assert.equal(premium.premium,true);assert.equal(premium.sampleCount,premiumSampleCount(sc));
 const rejectedAccess=computeManagedAccess(sc,{...baseState,quality:85,acceptedOffers:sc.offerHistory.accepted,offerDecisions:sc.offerHistory.decisions+1});assert.ok(rejectedAccess<sc.initial.access,`${type} one rejection should visibly reduce ranking`);assert.ok(rejectedAccess>=sc.initial.access-3,`${type} one rejection should not collapse ranking`);
 const seq=createSampleSequence(type,1234);assert.equal(new Set(seq).size,seq.length);assert.equal(seq.length,samplePoolSize(type));assert.ok(seq.length>=3+premiumSampleCount(sc));
 assert.deepEqual(authorityReference(type,'risk'),{primary:['worker'],secondary:[]},`${type} burden reference must measure who bears burden, not who causes it`);
 assert.deepEqual(authorityReference(type,'termination'),{primary:['platform'],secondary:[]},`${type} account-market access must not inherit client project power`);
}
const symmetricScenario={initial:{access:70}};const symmetricBase={baselineAcceptedOffers:50,baselineOfferDecisions:100,initialQuality:85,quality:85};const positive=computeManagedAccess(symmetricScenario,{...symmetricBase,acceptedOffers:55,offerDecisions:100});const negative=computeManagedAccess(symmetricScenario,{...symmetricBase,acceptedOffers:45,offerDecisions:100});assert.equal(positive-70,70-negative,'equal acceptance deltas must have symmetric ranking effects');assert.equal(positive,72);assert.equal(negative,68);
assert.equal(answerCredit(samples.translation[1],'B'),1);assert.equal(answerCredit(samples.translation[2],'A'),1);assert.equal(answerCredit(samples.translation[0],'B'),0);
for(const [type,rows] of Object.entries(samples))for(const [index,sample] of rows.entries()){
 assert.ok(sample.acceptable.includes(sample.preferred),`${type}[${index}] preferred must be acceptable`);
 assert.equal(sample.acceptable.some(value=>sample.reviewable.includes(value)),false,`${type}[${index}] acceptable/reviewable must not overlap`);
 for(const value of sample.reviewable){const grounds=sample.reviewableGrounds?.[value];assert.ok(Array.isArray(grounds)&&grounds.length>0,`${type}[${index}] reviewable ${value} needs grounds`);assert.ok(grounds.every(ground=>['guideline','context','technical'].includes(ground)),`${type}[${index}] has unknown appeal ground`)}
}
assert.deepEqual(authorityReferenceForState('data','termination',{contractDeclineEnding:true}),{primary:['platform'],secondary:[]});assert.deepEqual(authorityReferenceForState('translation','risk',{noWorkEnding:true}),{primary:['worker'],secondary:[]});assert.deepEqual(authorityReferenceForState('ai','termination',{noWorkEnding:true}),{primary:['platform'],secondary:[]});
for(const [type,model] of Object.entries(authorityModel))for(const axis of Object.keys(model)){const ref=authorityReference(type,axis);assert.ok(ref.primary.length>=1);assert.ok(ref.primary.every(p=>parties.includes(p)));assert.ok(ref.secondary.every(p=>parties.includes(p)));assert.deepEqual(authorityLeaders(type,axis),parties.filter(p=>ref.primary.includes(p)))}
assert.equal(powerAxisCredit({worker:0,platform:2,client:1},authorityReference('data','price')),1);assert.equal(powerAxisCredit({worker:0,platform:2,client:2},authorityReference('data','price'))<1,true,'invented tie must not get perfect credit');const noWorkAxes=analysisAxes({noWorkEnding:true});assert.deepEqual(noWorkAxes.map(a=>a.id),['price','allocation','risk','termination']);assert.equal(noWorkAxes.find(a=>a.id==='price').title,'قواعد تحديد السعر المعروضة في السوق');assert.equal(noWorkAxes.find(a=>a.id==='allocation').title,'قواعد توزيع فرص العمل المعروضة في السوق');assert.deepEqual(evidenceDimensions({noWorkEnding:true}),['contract','price','allocation','burden','access']);assert.equal(evidenceFor('payment',scenarios.data,{}).scoreable,false);assert.equal(evidenceFor('ownTools',scenarios.data,{}).preferredKind,'burden');
assert.equal(normalizeClaimKey('client+platform'),'platform+client');assert.equal(normalizeClaimKey('platform+client'),'platform+client');assert.equal(normalizeClaimKey('client+worker+platform'),'worker+platform+client');
const fullQuestions=questionsForState({scenarioKey:'data'}),noWorkQuestions=questionsForState({scenarioKey:'data',noWorkEnding:true}),contractQuestions=questionsForState({scenarioKey:'data',contractDeclineEnding:true});assert.equal(fullQuestions.length,5);assert.equal(noWorkQuestions[2].id,'noWorkBoundary');assert.equal(contractQuestions.length,1);assert.equal(acceptedQuestionAnswer(fullQuestions[0],fullQuestions[0].reference[0]),true);assert.equal(diagnosticFeedback(fullQuestions[0],fullQuestions[0].reference[0]).correct,true);
const noWorkPayment=buildPaymentSettlement(scenarios.data,{grossWorker:0,clientPaid:0,hold:0});assert.equal(noWorkPayment.mediator,0);assert.equal(noWorkPayment.transfer,0);assert.equal('net' in noWorkPayment,false);close(noWorkPayment.availableNet,-operatingCost(scenarios.data));close(noWorkPayment.economicPosition,noWorkPayment.availableNet);const noWorkAccess=assessAccessDecision(scenarios.data,{noWorkEnding:true,rejections:2});assert.equal(noWorkAccess.outcome,'warning');assert.doesNotMatch(noWorkAccess.factors[1].why,/خفض أولوية/);
const target0=dataTargetForScene(0);close(intersectionOverUnion(target0,target0),1);const semanticAnswers=[semanticDataAnswer(0,'leftCenter','standard'),semanticDataAnswer(1,'rightCenter','standard'),semanticDataAnswer(2,'center','standard')];assert.equal(scoreWork(scenarios.data,semanticAnswers,{sampleIndexes:[0,1,2]}),100);assert.equal(qualityAfterTask(90,60),80);const cleanRecord=taskRecord({id:'x',job:{id:'x',title:'x',pay:1,clientValue:2,duration:1},sampleIndexes:[0],answers:['A'],score:90,qualityBefore:90,qualityAfter:90,stressDelta:1,technicalIssue:true,technicalIssueSampleIndexes:[0]});assert.equal('technicalIssue' in cleanRecord,false);assert.deepEqual(cleanRecord.technicalIssueSampleIndexes,[0]);
const firstState={sampleSequence:[0,1,2,3,4,5],sampleCursor:0,currentTaskSampleIndexes:[0,1,2],completedTasks:[],workAnswers:semanticAnswers,quality:91,selectedJob:{id:'core',title:'مهمة',duration:12,pay:2.1,clientValue:5.8,stress:10},stress:24,time:0,paidTime:0,grossWorker:0,clientPaid:0};const firstTask=firstTaskOutcome(scenarios.data,firstState);assert.equal(firstTask.score,100);
const offerState={secondOffer:{id:'second-standard',title:'عرض',pay:1.8,duration:11},offerDecisions:20,acceptedOffers:15,rejections:0,acceptance:75,time:12,marketTime:4};const acceptedOffer=secondOfferDecision(offerState,true);assert.equal(acceptedOffer.time,12+SECOND_OFFER_DECISION_MINUTES);assert.equal(acceptedOffer.marketTime,4+SECOND_OFFER_DECISION_MINUTES);assert.equal(acceptedOffer.result.decisionMinutes,SECOND_OFFER_DECISION_MINUTES);const rejectedOffer=secondOfferDecision(offerState,false);assert.equal(rejectedOffer.rejections,1);assert.equal(rejectedOffer.time,14);
const secondBase={...firstState,...firstTask.changes,stress:95,secondOffer:{id:'second-premium',title:'دفعة مميزة',pay:3.85,duration:18,clientValue:8,premium:true,sampleCount:3,stress:16},offerDecisionResult:{accepted:true,decisionMinutes:2},currentTaskSampleIndexes:[3,4,5],secondTaskAnswers:[semanticDataAnswer(3,'left','short'),semanticDataAnswer(4,'right','short'),semanticDataAnswer(5,'center','wide')]};const second=completeSecondTask(scenarios.data,secondBase);assert.equal(second.changes.stress,100);assert.equal(second.stressDelta,5);assert.equal(monitorDecision({stress:42},true).stressAfter,42-BREAK_STRESS_REDUCTION);assert.equal(BREAK_MINUTES,3);
const riskBase={riskSeed:1,riskMode:'force-event',time:12,extraWorkTime:0,stress:30,riskEvent:null,completedTasks:[{id:'task-1',score:90,sampleIndexes:[0],technicalIssueSampleIndexes:[]},{id:'task-2',score:80,sampleIndexes:[1,2],technicalIssueSampleIndexes:[]}]};const forcedRisk=riskTransition(scenarios.data,riskBase);assert.equal(forcedRisk.event.occurred,true);assert.equal(forcedRisk.event.mode,'force-event');assert.equal(forcedRisk.event.affectedTaskId,'task-2');assert.equal(forcedRisk.event.affectedSampleIndex,2);assert.equal('technicalIssue' in forcedRisk.changes.completedTasks[1],false);assert.deepEqual(forcedRisk.changes.completedTasks[1].technicalIssueSampleIndexes,[2]);const forcedNone=riskTransition(scenarios.data,{...riskBase,riskEvent:null,riskMode:'force-none'});assert.equal(forcedNone.event.occurred,false);assert.equal(forcedNone.event.mode,'force-none');
const technicalAnswer={x:0,y:0,w:.05,h:.05,source:'visual'},reviewTask={id:'task-2',score:55,pay:3.85,answers:[technicalAnswer],sampleIndexes:[0],technicalIssueSampleIndexes:[0]};const reviewState={completedTasks:[reviewTask],reviewTaskId:'task-2',initialReviewSeverity:2,appealGround:'technical'};assert.ok(availableAppealGrounds(scenarios.data,reviewState).technical);const technicalReview=reviewAppeal(scenarios.data,reviewState);assert.equal(technicalReview.accepted,true);assert.equal(technicalReview.counterfactualScore,100);assert.equal(counterfactualAppealScore(scenarios.data,reviewTask,'technical'),100);const unrelated={...reviewTask,technicalIssueSampleIndexes:[5]};assert.equal(availableAppealGrounds(scenarios.data,{...reviewState,completedTasks:[unrelated]}).technical,undefined);
const unrelatedMixed={id:'task-2',score:30,pay:3.85,answers:[technicalAnswer,technicalAnswer,technicalAnswer],sampleIndexes:[0,1,2],technicalIssueSampleIndexes:[0]};const mixedState={completedTasks:[unrelatedMixed],reviewTaskId:'task-2',initialReviewSeverity:2,appealGround:'technical'};const mixedReview=reviewAppeal(scenarios.data,mixedState);assert.equal(mixedReview.counterfactualScore,33);assert.equal(mixedReview.accepted,false,'technical issue on one sample must not rescue multiple unrelated hard errors');
const translationTask={id:'task-1',score:60,pay:3,answers:['B'],sampleIndexes:[7]};const translationState={completedTasks:[translationTask],reviewTaskId:'task-1',initialReviewSeverity:1,appealGround:'guideline'};assert.equal(reviewProfile(scenarios.translation,translationTask).groundCounts.guideline,1);assert.ok(availableAppealGrounds(scenarios.translation,translationState).guideline);const translationReview=reviewAppeal(scenarios.translation,translationState);assert.equal(translationReview.accepted,true);assert.equal(translationReview.counterfactualScore,100);assert.equal(reviewAppeal(scenarios.translation,{...translationState,appealGround:'context'}).accepted,false);
const hardOnly={id:'task-1',score:30,pay:3,answers:['B'],sampleIndexes:[0]};assert.deepEqual(availableAppealGrounds(scenarios.translation,{completedTasks:[hardOnly],reviewTaskId:'task-1'}),{});
assert.equal(appealCostChanges({stress:99,time:0,extraWorkTime:0}).appealCost.stress,1);const major=disputeConsequences(reviewState,2);close(major.hold,.693);assert.equal(applyDisputeOutcome({qualityBeforeDispute:80,completedTasks:[{id:'task-1',pay:2}],reviewTaskId:'task-1',initialReviewSeverity:2,finalReviewSeverity:1}).changes.quality,76);
function perfectValues(ref){const out={worker:0,platform:0,client:0};ref.primary.forEach(p=>out[p]=2);ref.secondary.forEach(p=>out[p]=1);return out}
const perfectPower=Object.fromEntries(axes.map(a=>[a.id,perfectValues(authorityReference('data',a.id))]));const perfectEvidence=['contract','ownTools','priceSetting','allocation','monitoring','clientQuality','payment','accessDecision'],perfectSort={contract:'dep',ownTools:'burden',priceSetting:'ctrl',allocation:'ctrl',monitoring:'ctrl',clientQuality:'ctrl',accessDecision:'ctrl'},analysisState={evidence:perfectEvidence,evidenceSort:perfectSort,power:perfectPower,powerConfirmed:axes.map(a=>a.id)};assert.equal(powerMapComplete(analysisState),true);assert.equal(scoreAnalysis(scenarios.data,analysisState).score,100);
const contractPower={...perfectPower,termination:{worker:0,platform:2,client:0}},contractState={contractDeclineEnding:true,evidence:['contract','contractGate'],evidenceSort:{contract:'dep',contractGate:'ctrl'},power:contractPower,powerConfirmed:['termination']};assert.equal(scoreAnalysis(scenarios.data,contractState).powerScore,60);
assert.equal(selectReviewTask({completedTasks:[{id:'a',score:80},{id:'b',score:80}]}).id,'b');
console.log('No Boss domain checks passed');
