import {readFileSync,writeFileSync,existsSync,readdirSync,unlinkSync,rmdirSync} from 'node:fs';
import {resolve,dirname,relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {pages} from '../assets/js/core/routes.js';
import {APP_NAME,APP_VERSION} from '../assets/js/core/config.js';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const checkOnly=process.argv.includes('--check');
function rootShell(){return `<!doctype html>\n<html lang="ar" dir="rtl">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n<meta name="theme-color" content="#0d2742">\n<title>${APP_NAME} v${APP_VERSION}</title>\n<link rel="stylesheet" href="./assets/css/base.css">\n<link rel="stylesheet" href="./assets/css/layout.css">\n<link rel="stylesheet" href="./assets/css/components.css">\n<link rel="stylesheet" href="./assets/css/game.css">\n</head>\n<body data-page="home">\n<div class="app" id="app"></div>\n<script type="module" src="./assets/js/core/bootstrap.js"></script>\n</body>\n</html>\n`}
function routeShell(id,page){return `<!doctype html>\n<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d2742"><title>${page.title} | ${APP_NAME} v${APP_VERSION}</title><link rel="stylesheet" href="../assets/css/base.css"><link rel="stylesheet" href="../assets/css/layout.css"><link rel="stylesheet" href="../assets/css/components.css"><link rel="stylesheet" href="../assets/css/game.css"></head><body data-page="${id}"><div class="app" id="app"></div><script type="module" src="../assets/js/core/bootstrap.js"></script></body></html>\n`}
const expected=new Map([['index.html',rootShell()]]);for(const [id,page] of Object.entries(pages)){if(id!=='home')expected.set(`${page.slug}/index.html`,routeShell(id,page))}
function looksManagedShell(content){return content.includes('data-page=')&&content.includes('assets/js/core/bootstrap.js')&&content.includes('class="app" id="app"')}
let drift=false;
for(const [relativePath,content] of expected){const path=resolve(root,relativePath);if(checkOnly){if(!existsSync(path)||readFileSync(path,'utf8')!==content){console.error(`Route shell drift: ${relativePath}`);drift=true}}else writeFileSync(path,content,'utf8')}
for(const entry of readdirSync(root,{withFileTypes:true})){if(!entry.isDirectory()||entry.name.startsWith('.')||['assets','scripts','tests','node_modules'].includes(entry.name))continue;const path=resolve(root,entry.name,'index.html'),relativePath=relative(root,path).replaceAll('\\','/');if(!existsSync(path)||expected.has(relativePath))continue;const content=readFileSync(path,'utf8');if(!looksManagedShell(content))continue;if(checkOnly){console.error(`Orphan generated route shell: ${relativePath}`);drift=true}else{unlinkSync(path);if(readdirSync(resolve(root,entry.name)).length===0)rmdirSync(resolve(root,entry.name));console.log(`Removed orphan generated route shell: ${relativePath}`)}}
if(drift)process.exitCode=1;else console.log(checkOnly?'Route shells match the route manifest and no orphan shells remain':'Route shells generated from the route manifest');
