import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
import {APP_VERSION,ECONOMY_MODEL_VERSION} from '../assets/js/core/config.js';
import {pages} from '../assets/js/core/routes.js';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),read=path=>readFileSync(resolve(root,path),'utf8');
const routeFiles=['index.html',...Object.entries(pages).filter(([id])=>id!=='home').map(([,page])=>`${page.slug}/index.html`)];for(const file of routeFiles){assert.ok(existsSync(resolve(root,file)),`missing ${file}`);const source=read(file);assert.ok(source.includes('bootstrap.js'));assert.ok(source.includes(`No Boss v${APP_VERSION}`),`stale route ${file}`)}
const required=['assets/js/data/data-scenes.js','assets/js/data/authority-model.js','assets/js/data/task-guides.js','assets/js/data/parties.js','assets/js/core/state.js','assets/js/core/storage.js','assets/js/core/task-ui.js','assets/js/domain/analysis.js','assets/js/domain/dispute.js','assets/js/domain/payment.js','assets/js/domain/questions.js','assets/js/domain/work.js','assets/js/pages/work.js','assets/js/pages/management.js','assets/js/pages/power.js','assets/js/pages/conclusion.js','assets/js/pages/result.js','scripts/generate-pages.mjs','scripts/check.mjs','scripts/domain-check.mjs','scripts/semantic-invariants-check.mjs','tests/e2e/accessibility.spec.mjs','tests/e2e/journey.spec.mjs','package.json','.github/workflows/check.yml'];for(const file of required)assert.ok(existsSync(resolve(root,file)),`missing ${file}`);
const state=read('assets/js/core/state.js'),storage=read('assets/js/core/storage.js'),parties=read('assets/js/data/parties.js'),work=read('assets/js/pages/work.js'),management=read('assets/js/pages/management.js'),power=read('assets/js/pages/power.js'),conclusion=read('assets/js/pages/conclusion.js'),result=read('assets/js/pages/result.js'),components=read('assets/css/components.css');assert.ok(state.includes('STATE_SCHEMA_VERSION=5'));assert.ok(storage.includes('economyModelVersion'));assert.equal(ECONOMY_MODEL_VERSION,'2');assert.ok(parties.includes("ecosystemParties=['worker','platform','client','mediator']"));assert.ok(work.includes('taskSamplesHTML')&&work.includes('bindTaskInputs'));assert.ok(management.includes('أنهي الوردية الآن')&&management.includes('taskSamplesHTML'));assert.ok(!power.includes('powerEdited'));assert.ok(!conclusion.includes('needsCounter'));assert.ok(result.includes('ECONOMY_MODEL_VERSION'));assert.ok(!components.includes('.seg.mediator'));
const pkg=JSON.parse(read('package.json'));assert.equal(pkg.version,APP_VERSION);for(const script of ['check','check:routes','check:structural','check:regression','check:domain','check:semantic','check:syntax','test:e2e'])assert.ok(pkg.scripts[script],`missing npm script ${script}`);
console.log('No Boss structural guards passed');