import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),read=path=>readFileSync(resolve(root,path),'utf8');
const routeFiles=['index.html','scenario/index.html','onboarding/index.html','work/index.html','management/index.html','risk/index.html','dispute/index.html','payment/index.html','access/index.html','investigation/index.html','power/index.html','conclusion/index.html','result/index.html','rights/index.html'];for(const file of routeFiles){assert.ok(existsSync(resolve(root,file)),`missing ${file}`);const source=read(file);assert.ok(source.includes('bootstrap.js'),`missing bootstrap in ${file}`);assert.ok(source.includes('No Boss v3.0.2'),`missing current version title in ${file}`)}
const required=['assets/js/data/scenarios.js','assets/js/data/parties.js','assets/js/data/authority-model.js','assets/js/data/power-targets.js','assets/js/data/question-references.js','assets/js/data/evidence-templates.js','assets/js/data/samples.js','assets/js/core/config.js','assets/js/core/state.js','assets/js/core/storage.js','assets/js/core/routes.js','assets/js/core/ui.js','assets/js/core/bootstrap.js','assets/js/core/power-scoring.js','assets/js/domain/payment.js','assets/js/domain/access.js','assets/js/domain/evidence.js','assets/js/domain/questions.js','assets/js/domain/analysis.js','assets/js/domain/work.js','assets/js/domain/management.js','assets/js/domain/dispute.js','assets/js/domain/risk.js','scripts/check.mjs','scripts/domain-check.mjs','tests/e2e/smoke.spec.mjs','tests/e2e/journey.spec.mjs','playwright.config.mjs','package.json','.github/workflows/check.yml'];for(const file of required)assert.ok(existsSync(resolve(root,file)),`missing ${file}`);
const config=read('assets/js/core/config.js'),routes=read('assets/js/core/routes.js'),state=read('assets/js/core/state.js'),storage=read('assets/js/core/storage.js'),ui=read('assets/js/core/ui.js'),home=read('assets/js/pages/home.js'),scenario=read('assets/js/pages/scenario.js'),work=read('assets/js/pages/work.js'),management=read('assets/js/pages/management.js'),dispute=read('assets/js/pages/dispute.js'),payment=read('assets/js/pages/payment.js'),access=read('assets/js/pages/access.js'),investigation=read('assets/js/pages/investigation.js'),power=read('assets/js/pages/power.js'),conclusion=read('assets/js/pages/conclusion.js'),result=read('assets/js/pages/result.js'),rights=read('assets/js/pages/rights.js'),risk=read('assets/js/pages/risk.js'),scenarios=read('assets/js/data/scenarios.js'),samples=read('assets/js/data/samples.js'),authority=read('assets/js/data/authority-model.js'),domainAccess=read('assets/js/domain/access.js'),domainManagement=read('assets/js/domain/management.js'),domainDispute=read('assets/js/domain/dispute.js'),domainWork=read('assets/js/domain/work.js'),domainQuestions=read('assets/js/domain/questions.js'),domainAnalysis=read('assets/js/domain/analysis.js'),powerScoring=read('assets/js/core/power-scoring.js'),componentsCss=read('assets/css/components.css'),layoutCss=read('assets/css/layout.css'),gameCss=read('assets/css/game.css');
assert.ok(config.includes("APP_VERSION='3.0.2'"));
assert.ok(routes.includes("chapter:'worker'")&&routes.includes("chapter:'researcher'"));
for(const token of ['completedTasks','sampleSequence','sampleCursor','currentTaskSampleIndexes','marketExit','reviewTaskId','initialReviewSeverity','finalReviewSeverity'])assert.ok(state.includes(token),`state missing ${token}`);
assert.ok(storage.includes("STATE_KEY='no_boss_state'")&&storage.includes("RESULTS_KEY='no_boss_results'"));
assert.ok(authority.includes('authorityModel')&&authority.includes('leaders')&&authority.includes('distribution'));
assert.ok(scenarios.includes('premiumAt')&&scenarios.includes('jobStress')&&!scenarios.includes('outcomeStrictness'));
assert.ok(samples.includes('reviewable')&&samples.includes('مضايقة/إساءة')&&!samples.includes("preferred:'تحرش'"));
assert.ok(domainWork.includes('createSampleSequence')&&domainWork.includes('taskRecord')&&domainWork.includes('qualityAfterTask'));
assert.ok(work.includes('إنهاء الوردية دون قبول عمل')&&work.includes('marketExit:true')&&work.includes('nextSampleIndexes')&&work.includes('goal-strip')&&work.includes('مضايقة/إساءة'));
assert.ok(domainManagement.includes('premiumAt')&&domainManagement.includes('completedTasks')&&domainManagement.includes('qualityAfterTask')&&domainManagement.includes('prepareSecondTask'));
assert.ok(management.includes('أداؤك فتح العرض المميز فعلًا')&&management.includes('completedTasks')&&management.includes('جودة الحساب'));
assert.ok(domainDispute.includes('selectReviewTask')&&domainDispute.includes('reviewableErrors')&&domainDispute.includes('reviewTaskId'));
assert.ok(dispute.includes('المهمة محل النزاع')&&dispute.includes('لم تستخدم المراجعة أي إجابة من مهمة أخرى'));
assert.ok(domainAccess.includes("points===0?'active'")&&domainAccess.includes('rejectionPoints')&&!domainAccess.includes('qualityPoints'));
assert.ok(payment.includes('payment-flow')&&payment.includes('money-ltr')&&payment.includes('actor-icon'));
assert.ok(access.includes('انتهى الفصل الأول: وردية العامل')&&access.includes('لم تُنفذ مهمة'));
assert.ok(investigation.includes('آخر الوقائع المهمة')&&investigation.includes('دليل مختلط / يحتاج سياقًا'));
assert.ok(domainQuestions.includes('questionsForState')&&domainAnalysis.includes('analysisAxes')&&domainAnalysis.includes('evidenceDimensions'));
assert.ok(power.includes('step="5"')&&power.includes('paintCard')&&power.includes('المحاور ${active.length}')&&!power.includes('type="number"'));
assert.ok(powerScoring.includes('distributionProximity')&&powerScoring.includes('.4*leaderCredit+.6*distributionProximity'));
assert.ok(conclusion.includes('conclusionEvidence.length<minimum')&&conclusion.includes('evidence-group')&&conclusion.includes('analysisAxes(state).length'));
assert.ok(result.includes('هدف المقابل')&&result.includes('completedTasks')&&result.includes('المهمة التي خضعت للمراجعة'));
assert.ok(rights.includes('eventReasons')&&rights.includes('contextReasons')&&rights.includes('حدث فعلي')&&rights.includes('سياق'));
assert.ok(home.includes('عالم المحاكاة خيالي')&&scenario.includes('محاكاة خيالية'));
assert.ok(risk.includes('actor-icon'));
assert.ok(ui.includes('compact-stats')&&ui.includes('summaryToggle'));
assert.ok(componentsCss.includes('.task-now')&&componentsCss.includes('.actor-card')&&componentsCss.includes('.money-ltr'));
assert.ok(layoutCss.includes('.compact-stats')&&layoutCss.includes('.summary-details.open'));
for(const token of ['.goal-strip','.right-reason','.evidence-group','.task-result-grid'])assert.ok(gameCss.includes(token),`game css missing ${token}`);
const pkg=JSON.parse(read('package.json'));for(const script of ['check','check:routes','check:structural','check:regression','check:domain','check:syntax','test:e2e'])assert.ok(pkg.scripts[script],`missing npm script ${script}`);
console.log('No Boss structural guards passed');
