import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=path=>readFileSync(resolve(root,path),'utf8');
const routeFiles=['index.html','scenario/index.html','onboarding/index.html','work/index.html','management/index.html','risk/index.html','dispute/index.html','payment/index.html','access/index.html','investigation/index.html','power/index.html','conclusion/index.html','result/index.html','rights/index.html'];
for(const file of routeFiles){const path=resolve(root,file);assert.ok(existsSync(path),`missing ${file}`);const source=read(file);assert.ok(source.includes('bootstrap.js'),`missing bootstrap in ${file}`);assert.ok(source.includes('No Boss v3.0.2'),`missing current version title in ${file}`)}

const required=['assets/js/data/scenarios.js','assets/js/data/parties.js','assets/js/data/power-targets.js','assets/js/data/question-references.js','assets/js/data/evidence-templates.js','assets/js/data/samples.js','assets/js/core/config.js','assets/js/core/html.js','assets/js/core/state.js','assets/js/core/storage.js','assets/js/core/routes.js','assets/js/core/ui.js','assets/js/core/bootstrap.js','assets/js/core/power-scoring.js','assets/js/domain/payment.js','assets/js/domain/access.js','assets/js/domain/evidence.js','assets/js/domain/questions.js','assets/js/domain/analysis.js','assets/js/domain/work.js','assets/js/domain/management.js','assets/js/domain/dispute.js','assets/js/domain/risk.js','assets/images/no-boss-logo.svg','scripts/check.mjs','scripts/domain-check.mjs','scripts/generate-pages.mjs','scripts/serve-static.mjs','scripts/syntax-check.mjs','tests/e2e/smoke.spec.mjs','tests/e2e/journey.spec.mjs','playwright.config.mjs','package.json','DEPLOY_GITHUB_AR.txt','.github/workflows/check.yml'];
for(const file of required)assert.ok(existsSync(resolve(root,file)),`missing ${file}`);

const config=read('assets/js/core/config.js');
const routes=read('assets/js/core/routes.js');
const state=read('assets/js/core/state.js');
const storage=read('assets/js/core/storage.js');
const bootstrap=read('assets/js/core/bootstrap.js');
const ui=read('assets/js/core/ui.js');
const home=read('assets/js/pages/home.js');
const power=read('assets/js/pages/power.js');
const conclusion=read('assets/js/pages/conclusion.js');
const work=read('assets/js/pages/work.js');
const management=read('assets/js/pages/management.js');
const dispute=read('assets/js/pages/dispute.js');
const investigation=read('assets/js/pages/investigation.js');
const rights=read('assets/js/pages/rights.js');
const result=read('assets/js/pages/result.js');
const payment=read('assets/js/pages/payment.js');
const access=read('assets/js/pages/access.js');
const analysis=read('assets/js/domain/analysis.js');
const evidence=read('assets/js/domain/evidence.js');
const questions=read('assets/js/domain/questions.js');
const domainWork=read('assets/js/domain/work.js');
const domainCheck=read('scripts/domain-check.mjs');
const gameCss=read('assets/css/game.css');
const deploy=read('DEPLOY_GITHUB_AR.txt');
const workflow=read('.github/workflows/check.yml');
const generator=read('scripts/generate-pages.mjs');
const syntaxCheck=read('scripts/syntax-check.mjs');
const playwright=read('playwright.config.mjs');
const e2e=read('tests/e2e/smoke.spec.mjs');
const journey=read('tests/e2e/journey.spec.mjs');
const pkg=JSON.parse(read('package.json'));

assert.ok(config.includes("APP_NAME='No Boss'")&&config.includes("APP_VERSION='3.0.2'")&&config.includes('RESULT_VERSION'));
assert.ok(routes.includes("scenario:{slug:'scenario',stage:0")&&routes.includes("result:{slug:'result',stage:11")&&routes.includes('isPublicPage')&&routes.includes('isResearcherPage')&&routes.includes('pageForStage'));
assert.ok(state.includes("import {axes} from '../data/parties.js'")&&state.includes('latestStateRevision')&&state.includes('storageWriterId')&&state.includes('export function commit'));
assert.ok(state.includes("checkpoint(page,{persistNow:false})")&&state.includes('if(state.currentPage===page)return state')&&state.includes('routePageForStage')&&state.includes('routeStageForPage'));
assert.ok(storage.includes("const STATE_KEY='no_boss_state'")&&storage.includes("const RESULTS_KEY='no_boss_results'")&&storage.includes('latestStateRevision')&&storage.includes('compareStateCandidates')&&storage.includes('compactResult'));
assert.ok(storage.includes('writePersistent')&&storage.includes('stateStorageMode')&&storage.includes('function local(){try')&&storage.includes('function session(){try'));
assert.ok(bootstrap.includes("stageForPage,isPublicPage")&&bootstrap.includes('isPublicPage(page)')&&bootstrap.includes('pageForStage(currentStage)')&&bootstrap.includes('beforeunload'));
assert.ok(ui.includes("page==='rights'?consumeCheckpointTo('result'):undoCheckpoint()")&&ui.includes('isResearcherPage(page)')&&ui.includes('role="progressbar"'));
assert.ok(home.includes("from '../core/config.js'")&&home.includes("from '../core/storage.js'")&&home.includes('resumePage')&&home.includes('savedResults')&&home.includes('<caption'));
assert.ok(rights.includes('consumeCheckpointTo')&&rights.includes('updateSummary'));
assert.ok(power.includes("from '../data/parties.js'")&&power.includes('powerDraft')&&power.includes('rawValuesFor')&&power.includes('escapeAttribute'));
assert.ok(conclusion.includes('powerMapComplete')&&conclusion.includes('scoreAnalysis')&&conclusion.includes("from '../domain/evidence.js'")&&conclusion.includes("from '../domain/analysis.js'"));
assert.ok(work.includes("from '../data/scenarios.js'")&&work.includes("from '../data/samples.js'")&&work.includes("from '../domain/work.js'")&&work.includes('firstTaskOutcome')&&work.includes('commit({')&&work.includes('ResizeObserver'));
assert.ok(management.includes("from '../domain/management.js'")&&management.includes('secondOfferDecision')&&management.includes('monitorDecision')&&management.includes('commit({'));
assert.ok(dispute.includes("from '../data/samples.js'")&&dispute.includes("from '../domain/dispute.js'")&&dispute.includes('publishedTranslationText')&&dispute.includes('applyDisputeOutcome')&&dispute.includes('commit({'));
assert.ok(investigation.includes('role="tabpanel"')&&investigation.includes('aria-controls')&&investigation.includes("from '../domain/evidence.js'")&&investigation.includes("from '../domain/questions.js'"));
assert.ok(payment.includes("from '../domain/payment.js'")&&payment.includes('commit({'));
assert.ok(access.includes("from '../domain/access.js'")&&access.includes('commit({'));
assert.ok(result.includes("from '../data/parties.js'")&&result.includes("from '../data/power-targets.js'")&&result.includes('archiveCurrentResult')&&result.includes('archiveResult({')&&result.includes('تعذر حفظ النتيجة'));
assert.ok(analysis.includes("from '../data/parties.js'")&&analysis.includes("from '../data/power-targets.js'"));
assert.ok(evidence.includes("from '../data/evidence-templates.js'"));
assert.ok(questions.includes("from '../data/question-references.js'"));
assert.ok(domainWork.includes("from '../data/samples.js'"));
assert.ok(domainCheck.includes('data/parties.js')&&domainCheck.includes('data/power-targets.js'));
assert.ok(gameCss.includes('.archive-table')&&gameCss.includes('.analysis-input')&&gameCss.includes('.drawbox{position:absolute;display:none'));
assert.ok(generator.includes("import {pages} from '../assets/js/core/routes.js'")&&generator.includes("process.argv.includes('--check')"));
assert.ok(syntaxCheck.includes("execFileSync(process.execPath,['--check',file]")&&syntaxCheck.includes("roots=['assets/js','scripts','tests']"));
for(const script of ['check','check:routes','check:structural','check:regression','check:domain','check:syntax','test:e2e'])assert.ok(pkg.scripts[script],`missing npm script ${script}`);
assert.ok(pkg.devDependencies['@playwright/test']);
assert.ok(playwright.includes("name:'chromium'")&&playwright.includes("name:'mobile-chromium'")&&playwright.includes('serve-static.mjs'));
assert.ok(e2e.includes('startDataScenario')&&e2e.includes('home resume returns to current active stage')&&e2e.includes('direct protected route without state returns home'));
assert.ok(journey.includes('complete worker-to-researcher journey reaches result and rights')&&journey.includes('startModerationScenario')&&journey.includes("expect(saved.stage).toBe(11)"));
assert.ok(deploy.includes('محتويات المشروع كاملة')&&deploy.includes('مجلد assets/ كاملًا'));
for(const script of ['check:routes','check:structural','check:regression','check:domain','check:syntax','test:e2e'])assert.ok(workflow.includes(`npm run ${script}`),`workflow does not run ${script}`);

console.log('No Boss structural guards passed');
